on:
  workflow_dispatch

jobs:

  build:
    # Windows is currently the only platform this action supports
    runs-on: windows-2019

    steps:

      # Check-out repository
      - uses: actions/checkout@v3

      - name: Install Visual C++ Redistributable
        run: |
          choco install vcredist2015

      # Setup Python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
          cache: 'pip'
      #   cache-dependency-path: |
      #     **/requirements*.txt
            
      # Install dependencies
      - name: Install Dependencies
        run: |
          pip install poetry
          poetry config virtualenvs.in-project true
          poetry install --no-root
          poetry env use .\.venv\Scripts\python.exe
          poetry run python .\python-env.py
          echo $PATH

      # Build zip folder with executable using pyinstaller
      - name: Build zip file
        run: |
          cp .\.github\pyinstaller\gesture-mouse.spec.win gesture-mouse.spec
          poetry run pyinstaller.exe gesture-mouse.spec --clean --noconfirm
      # pyinstaller gui.py -D --add-data config:config --add-data data:data --collect-all mediapipe -n gesture-mouse --contents-directory .

      # Uploads artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: gesture-mouse
          path: dist/gesture-mouse
